### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by jameswhang** [PerfDevTeam/perf_back#20]
We broke an endpoint and tests caught it, but CI is not integrated so nothing caught this. 

```
======================================================================
ERROR: test_notbought_post_get (test_notbought.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jameswhang/Documents/projects/perf_back/tests/test_notbought.py", line 94, in test_notbought_post_get
    self.assertEqual(get_data['response'][0]['name'], 'san')
KeyError: 'response'

======================================================================
FAIL: test_bought_post_get (test_bought.BasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jameswhang/Documents/projects/perf_back/tests/test_bought.py", line 97, in test_bought_post_get
    self.assertEqual(get_bought.status_code, 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 10 tests in 0.388s
```
This is a regression introduced from https://github.com/PerfDevTeam/perf_back/commit/9a5ee7abc59a46af2ae4d7ff7f1c422280ec1aae

**Comment by jameswhang** [comment]
@yulheekim please run tests before submitting PR.

**Comment by jameswhang** [comment]
Fuck this. I'll just rewrite the whole view.
